### ISSUE TITLE
Separate the example-project to another repo

### ISSUE THREAD

**Issue by Ashark** [winseros/Qt6Renderer#10]
Hi.

Can you consider moving the example-project to a separate repository? This way it will be easier to work with, because I would like to test it with different IDEs, and it would be more convenient. Currently, even for clion, I need to have a separate .idea directory in a project that is actually a plugin itself.

**Comment by emmenlau** [comment]
Dear @Ashark , are you using this project with VSCode? I would be very interested in this...

**Comment by Ashark** [comment]
@emmenlau Not _actually_ using right now, but want to explore what results are possible to achieve in vscode also.
If you are interested, this is the issue that tracks this: https://invent.kde.org/sdk/kde-builder/-/issues/85

I guess it may be possible to reuse the qt6 pretty printers from this project (Qt6Renderer) in the vscode.

For vscode specifically, they say that a subset of natvis framework is implemented, but it did not worked for me at all, see https://invent.kde.org/sdk/kde-builder/-/issues/85#note_994738

**Comment by emmenlau** [comment]
Hey @Ashark , very nice, I would really appreciate this! I've previously looked at debugger integrations for VSCode and I am under the impression that they share quite some similarity with clion (what this project provides).

About natvis, I did try to get this to work something like 6 months ago. However shortly into the project, I got the impression that natvis is Windows / MSVC-only. This was not so obvious from a first look, but diving a bit deeper it seemed that its Windows / MSVC only (albeit I do not recall the specific reasons). I guess for KDE-development, you'd want cross-platform support?

**Comment by Ashark** [comment]
> However shortly into the project, I got the impression that natvis is Windows / MSVC-only.

Me too, but I found out that the official doc at least pretends that non-msvc do have some support, see https://github.com/tonka3000/vscode-qt-tools/pull/95/commits/18f1bbe11ed0e648c5b1a492c52b3f1388ec0e71

I suggest to discuss that in that mr, and keep the current issue on topic (separating the example project).

**Comment by winseros** [comment]
> Hi.
> 
> Can you consider moving the example-project to a separate repository? This way it will be easier to work with, because I would like to test it with different IDEs, and it would be more convenient. Currently, even for clion, I need to have a separate .idea directory in a project that is actually a plugin itself.

I was about to answer no, but after reading the conversation, I decided that I should give it some more thought. I might be able to make a comparable `VSCode` plugin if I can find enough spare time. If so, I will divide up the present source code into the following repositories: "example project", "JetBrans plugin", "vscode plugin" and "core logic". I'm looking at the VSCode plugin API to see what I can get out of it.

**Comment by emmenlau** [comment]
Whow, two thumbs up for your initiative, @winseros ! There are quite many VSCode users nowadays, so your work would certainly be appreciated!

**Comment by Ashark** [comment]
> I might be able to make a comparable `VSCode` plugin if I can find enough spare time

Wow, that would be awesome!

**Comment by winseros** [comment]
The good news it did work, at least with `GDB`. I have not tried `LLDB` yet, but I assume it would work too.

![image](https://github.com/user-attachments/assets/18941767-b5ba-4a97-9275-40a925a0a4b3)

**Comment by emmenlau** [comment]
Awesome!!!

**Comment by winseros** [comment]
Hi. I began to split the codebase.

I left only python scripts in the current repository and created new repos for the example project and for the Intellij plugin.

https://github.com/winseros/Qt6RendererExmpl
https://github.com/winseros/Qt6RendererIntlj

The VSCode repo is on the way.

**Comment by winseros** [comment]
I uploaded the VSCode extension code to the repository. 

https://github.com/winseros/Qt6RendererVsc

Have not yet completed any `README` work or marketplace publishing.

I tested it in Linux using `LLDB` and `GDB`, and I'll check it on Windows as well. Since I don't have MacOS, I'll let enthusiasts handle this task, but I assume it should also work there.

**Comment by winseros** [comment]
Hi, I published a pre-release version of the extension. 

https://marketplace.visualstudio.com/items?itemName=knv.qt6renderer

Waiting for your feedback, and will publish a release if everything is fine.

**Comment by Merrit** [comment]
Very nice! :tada: 

I am definitely seeing visualizations for some things I usually never get, like `QDir`.

Some things are not working. I looked through the troubleshooting section..

In GDB I did `info sharedlibrary`:

```
From                To                  Syms Read   Shared Object Library
0x00007ffff7fc9000  0x00007ffff7ff09f5  Yes         /lib64/ld-linux-x86-64.so.2
0x00007ffff7df0a80  0x00007ffff7f21ffe  Yes         /lib64/libQt6Network.so.6
0x00007ffff7538640  0x00007ffff7be8b8a  Yes         /lib64/libQt6Gui.so.6
0x00007ffff6ccb180  0x00007ffff70b67f8  Yes         /lib64/libQt6Core.so.6
0x00007ffff7d666d0  0x00007ffff7d80011  Yes         /lib64/libGLX.so.0
0x00007ffff73ea1b0  0x00007ffff73ea684  Yes         /lib64/libOpenGL.so.0
...
```

Which seems as expected.

The other check doesn't seem to work:

```
(gdb) python print(gdb.parse_and_eval('*(&qtHookData)'))
<data variable, no debug info>
```

This is on Fedora 40, with Qt 6.7.2. I checked that I have installed `qt6-qtbase`, `qt6-qtbase-devel`, `qt6-qtbase-debuginfo`, and `qt6-qtbase-debugsource`. @Ashark had a similar result, but interestingly when switching from VS Code to CLion, the CLion terminal worked normally with that python command.

First example of printer only partially working for me is QString:

![image](https://github.com/user-attachments/assets/49fdc37c-f77f-4124-8af2-c70c29c77e86)

**Comment by Merrit** [comment]
> I eventually decided that pointer dereference was outside the scope of Qt-specific pretty printers, thus I disabled pointer values pretty printing.

That's interesting; if one is debugging and hits a breakpoint, and only a pointer is in scope; wouldn't we likely _want_ to see the value?

-----

QHash looks a bit odd, unless that is intended:

![image](https://github.com/user-attachments/assets/41d62a28-eeb0-413b-bb15-64fdea4f786b)

QList:

![image](https://github.com/user-attachments/assets/fa9cbc85-db90-47c2-a530-99c77bc5c784)

QMap:

![image](https://github.com/user-attachments/assets/3641bdff-0256-46ed-82bb-b6dc138a2513)

QVariant:

![image](https://github.com/user-attachments/assets/75a7397d-35b8-4d9f-9813-1146b12d8f41)

-----

Maybe some or all of these were intentional, but they were what stood out to me.

**Comment by winseros** [comment]
@Merrit the screenshots are very far from intentional. I would verify if the debug symbols correspond with the binary files.

Could you try running the example with the Qt version that comes from the Qt installer rather than the Fedora repository? I also would be interested if `python print(gdb.parse_and_eval('*(&qtHookData)'))` gives expected results there.

**Comment by Merrit** [comment]
I installed Qt from the online installer, including the Qt Debug Information Files:

![image](https://github.com/user-attachments/assets/bfab3e6d-451b-4194-b7a0-6a11b688725f)

Looks like it is using them:

```
(gdb) info sharedlibrary
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
From                To                  Syms Read   Shared Object Library
0x00007ffff7fc9000  0x00007ffff7ff09f5  Yes         /lib64/ld-linux-x86-64.so.2
0x00007ffff7e3ab90  0x00007ffff7f4bd1a  Yes         /home/merritt/Applications/tools/Qt/6.7.2/gcc_64/lib/libQt6Network.so.6
0x00007ffff7320540  0x00007ffff7a2c5f2  Yes         /home/merritt/Applications/tools/Qt/6.7.2/gcc_64/lib/libQt6Gui.so.6
0x00007ffff6ab7670  0x00007ffff6e9fceb  Yes         /home/merritt/Applications/tools/Qt/6.7.2/gcc_64/lib/libQt6Core.so.6
0x00007ffff7d846d0  0x00007ffff7d9e011  Yes         /lib64/libGLX.so.0
0x00007ffff7d6c1b0  0x00007ffff7d6c684  Yes         /lib64/libOpenGL.so.0
0x00007ffff66a5580  0x00007ffff67d4232  Yes         /lib64/libstdc++.so.6
0x00007ffff7c87440  0x00007ffff7cfe666  Yes         /lib64/libm.so.6
0x00007ffff7c4d780  0x00007ffff7c70455  Yes         /lib64/libgcc_s.so.1
0x00007ffff6437800  0x00007ffff65a3cfd  Yes         /lib64/libc.so.6
0x00007ffff71b6e40  0x00007ffff71f2238  Yes         /lib64/libgssapi_krb5.so.2
0x00007ffff7c45050  0x00007ffff7c45115  Yes         /lib64/libpthread.so.0
0x00007ffff7c232c0  0x00007ffff7c38541  Yes         /lib64/libz.so.1
0x00007ffff7c12700  0x00007ffff7c1adc9  Yes         /lib64/libresolv.so.2
0x00007ffff7c007b0  0x00007ffff7c093f4  Yes         /lib64/libEGL.so.1
0x00007ffff7161f30  0x00007ffff719009e  Yes         /lib64/libfontconfig.so.1
0x00007ffff68d7480  0x00007ffff69697ee  Yes         /lib64/libX11.so.6
0x00007ffff7157050  0x00007ffff7157115  Yes         /lib64/libdl.so.2
0x00007ffff62e1040  0x00007ffff6382c52  Yes         /lib64/libglib-2.0.so.0
0x00007ffff621bc10  0x00007ffff6299c14  Yes         /home/merritt/Applications/tools/Qt/6.7.2/gcc_64/lib/libQt6DBus.so.6
0x00007ffff7110a30  0x00007ffff712fd80  Yes         /lib64/libxkbcommon.so.0
0x00007ffff61b41d0  0x00007ffff61b70d1  Yes         /lib64/libGL.so.1
0x00007ffff60c2830  0x00007ffff6153d9a  Yes         /lib64/libfreetype.so.6
0x00007ffff7109090  0x00007ffff71091cd  Yes         /lib64/libgthread-2.0.so.0
0x00007ffff5cf9780  0x00007ffff5ea6455  Yes (*)     /home/merritt/Applications/tools/Qt/6.7.2/gcc_64/lib/libicui18n.so.73
0x00007ffff586a440  0x00007ffff596f240  Yes (*)     /home/merritt/Applications/tools/Qt/6.7.2/gcc_64/lib/libicuuc.so.73
                                        Yes (*)     /home/merritt/Applications/tools/Qt/6.7.2/gcc_64/lib/libicudata.so.73
0x00007ffff7102090  0x00007ffff71022c1  Yes         /lib64/librt.so.1
0x00007ffff70f17b0  0x00007ffff70fbdae  Yes         /lib64/libXext.so.6
0x00007ffff60442d0  0x00007ffff604629f  Yes         /lib64/libGLdispatch.so.0
0x00007ffff5f90080  0x00007ffff5ff7fbd  Yes         /lib64/libkrb5.so.3
0x00007ffff68a8fc0  0x00007ffff68b4a1c  Yes         /lib64/libk5crypto.so.3
0x00007ffff70e6490  0x00007ffff70e7081  Yes         /lib64/libcom_err.so.2
0x00007ffff6898f80  0x00007ffff689fbf8  Yes         /lib64/libkrb5support.so.0
0x00007ffff688d4b0  0x00007ffff688e726  Yes         /lib64/libkeyutils.so.1
0x00007ffff3250000  0x00007ffff358dd22  Yes         /lib64/libcrypto.so.3
0x00007ffff5acb040  0x00007ffff5bb3513  Yes         /lib64/libxml2.so.2
0x00007ffff5f5be50  0x00007ffff5f6eebe  Yes         /lib64/libxcb.so.1
0x00007ffff5762500  0x00007ffff57d467c  Yes         /lib64/libpcre2-8.so.0
0x00007ffff5a5ecd0  0x00007ffff5a8d6db  Yes         /lib64/libdbus-1.so.3
0x00007ffff6877550  0x00007ffff68840e3  Yes         /lib64/libbz2.so.1
0x00007ffff572c250  0x00007ffff57543ad  Yes         /lib64/libpng16.so.16
0x00007ffff36f1640  0x00007ffff37ca9b2  Yes         /lib64/libharfbuzz.so.0
0x00007ffff68681f0  0x00007ffff686fafa  Yes         /lib64/libbrotlidec.so.1
0x00007ffff5a28130  0x00007ffff5a4274c  Yes         /lib64/libselinux.so.1
0x00007ffff56f6af0  0x00007ffff57183ff  Yes         /lib64/liblzma.so.5
0x00007ffff5a1c3d0  0x00007ffff5a1d122  Yes         /lib64/libXau.so.6
0x00007ffff3125ac0  0x00007ffff31bde20  Yes         /lib64/libsystemd.so.0
0x00007ffff56d52d0  0x00007ffff56ec26c  Yes         /lib64/libgraphite2.so.3
0x00007ffff56b10f0  0x00007ffff56b17de  Yes         /lib64/libbrotlicommon.so.1
0x00007ffff56a6950  0x00007ffff56ab630  Yes         /lib64/libcap.so.2
0x00007ffff36c5550  0x00007ffff36dfc66  Yes         /lib64/liblz4.so.1
0x00007ffff3057e80  0x00007ffff3102472  Yes         /lib64/libzstd.so.1
                                        No          linux-vdso.so.1
```

This one is still the same:

```
(gdb) python print(gdb.parse_and_eval('*(&qtHookData)'))
<data variable, no debug info>
```

No change in the visualizations at breakpoints as far as I can see.

**Comment by winseros** [comment]
Could you then attempt to use the [same plugin](https://plugins.jetbrains.com/plugin/19882-qt6-renderer) in `CLion`? You mentioned `python print(gdb.parse_and_eval('*(&qtHookData)'))` worked as it had to work in `CLion`, and I'm curious if pretty printing would also work.

**Comment by Merrit** [comment]
Unfortunately I don't have a license for CLion. @Ashark, have you tried the extensions in VS Code / CLion?

**Comment by Ashark** [comment]
Works for me everywhere: CLion, VS Code, Konsole. For the note, I am on Arch Linux, using distro-provided qt (currently 6.7.2-2).

**Comment by winseros** [comment]
> Unfortunately I don't have a license for CLion. @Ashark, have you tried the extensions in VS Code / CLion?

@Merrit, then lets check the other things:

- GDB Version
- CMake command line
  <details>
    <summary>You may find it in the output window, when initiating CMake configuration</summary>
    
    For Linux it looks quite similar.

    ![image](https://github.com/user-attachments/assets/3f77c277-dc66-46b3-ba70-34bc383a7cdc)
  
  </details>
- `launch.json` configuration

**Comment by Merrit** [comment]
I believe my existing Qt pretty printers were causing some conflict, I realized that config was still present while troubleshooting this issue. My bad!

I commented out my existing `.gdbinit`, and this seems to have improved the situation, as a lot of the things that seemed broken before now seem to work or partially work. Some things still don't seem to load:

![image](https://github.com/user-attachments/assets/6a3ec9af-8655-4ece-9302-3ed95d15f44e)

![image](https://github.com/user-attachments/assets/2c65b09a-a582-43f0-9aab-72f6ac8d4d40)

![image](https://github.com/user-attachments/assets/15823c1a-566d-475f-9cba-1751036ddca7)

QVariant looks pretty good now!:

![image](https://github.com/user-attachments/assets/55353d5c-4026-4ae4-ba4c-49c68097ca2a)

**GDB Version:** GNU gdb (Fedora Linux) 14.2-3.fc40
**CMake command:** `[proc] Executing command: /usr/bin/cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -S/home/merritt/Downloads/qt-pretty-printers/Qt6RendererExmpl -B/home/merritt/Downloads/qt-pretty-printers/Qt6RendererExmpl/build`

**launch.json:**

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug QTTypesExample",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/QTTypesExample",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "preLaunchTask": "build",
            "miDebuggerPath": "/usr/bin/gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "logging": {
                "engineLogging": true
            },
        }
    ]
}
```

---

One difference I've noticed is the python evaluation is different between the system Qt and the version from the online installer (though the results seem the same).

**System Qt:**

```
-exec python print(gdb.parse_and_eval('*(&qtHookData)'))
1: (50444) <-1077-interpreter-exec console "python print(gdb.parse_and_eval('*(&qtHookData)'))"
1: (50444) ->~"0x7ffff729bd00 <qtHookData>\n"
1: (50445) ->1077^done
1: (50445) ->(gdb)
1: (50445) 1077: elapsed time 0
0x7ffff729bd00 <qtHookData>
```

**Online installer:**

```
-exec python print(gdb.parse_and_eval('*(&qtHookData)'))
1: (66172) <-1074-interpreter-exec console "python print(gdb.parse_and_eval('*(&qtHookData)'))"
1: (66173) ->~"{3, 7, 395010, 0, 0, 0, 22}\n"
1: (66173) ->1074^done
1: (66173) ->(gdb)
1: (66173) 1074: elapsed time 0
{3, 7, 395010, 0, 0, 0, 22}
```

**Comment by winseros** [comment]
@Merrit `.gdbinit` is what I absolutely forgot about. Now I added the notice to the [Troubleshooting](https://github.com/winseros/Qt6Renderer/?tab=readme-ov-file#troubleshooting) section.

Regarding the configuration you shared - everything appears fine. I would not have a glue in the configuration if you had not mentioned `.gdbinit`. :smiley: 

But the screenshots still look wierd. Can we try two more things:

1. Ensure there are no conflicting printers in `GDB`.
    ```
   -exec info pretty-printer
    ```
   normally prints something like:
   ```
   global pretty-printers:
    builtin
      mpx_bound128
    qt6_lookup
   objfile /usr/lib/libstdc++.so.6 pretty-printers:
     libstdc++-v6
   ```
2. Try to press `Step Over` several times. Sometimes IDE might display (well, not the IDE, but the debugger) it has reached the end of the method, while it has not.

   <details>
       <summary>How it works in my environment. Lots of text and screenshots.</summary>

      **Step1**: We've traveled part of the code in the method. IDE displays garbage in most of the variables. Like on your screenshot.
     
     ![image](https://github.com/user-attachments/assets/149e8ae5-e651-49ed-a662-89b6788898fd)

     **Step2**: We've pressed `Step Over (F10)` once. IDE now thinks we're at the end of the method and displays a weird variables state.

     ![image](https://github.com/user-attachments/assets/c8d3dacd-950e-48d0-826d-c39b06a4957c)

     **Step3**: One more time `Step Over (F10)`. Jumbed back in the middle of the method. Variables still in a weird state.

     ![image](https://github.com/user-attachments/assets/1f769843-2f1a-4d9b-b2ce-9d97d52dfaf2)

     **Step4**: Press `Step Over (F10)` several times untill IDE reaches the line `25`. Two more variables got values.

     ![image](https://github.com/user-attachments/assets/83aa46e2-4ff0-400c-af16-3953f3de91d6)

    **Next steps**: Press `Step Over (F10)` and move down and down. More and more variables get values.
 
   </details>

   I wonder if things function the same in your environment as they do in mine.

**Comment by Merrit** [comment]
Nice find!

Very strange behaviour by the IDE, never seen it jump around like that. The issue indeed seems to be having the breakpoint on the closing brace, it breaks there even though it hasn't gone through the function!

If instead I step through the function, or put the breakpoint on the last _line_ of the function it works as expected! :tada:

![image](https://github.com/user-attachments/assets/ff8a6420-b143-4bb4-a3c8-72084a656a64)

Also, this is the report on pretty printers..

`-exec info pretty-printer`:

```
global pretty-printers:
  builtin
    mpx_bound128
  qt6_lookup
  unknown
objfile /lib64/libstdc++.so.6 pretty-printers:
  libstdc++-v6
objfile /lib64/libglib-2.0.so.0 pretty-printers:
  pretty_printer_lookup
objfile /lib64/libgobject-2.0.so.0 pretty-printers:
  pretty_printer_lookup
  ```

So I think that means it is working as expected! Thank you for your help figuring that out. :tada: :blue_heart:

**Comment by winseros** [comment]
Hi, @Merrit. Neither the IDE nor the debugger are to blame for this behavior. The behavior is the same when you open the project, for example, in `CLion` and use `LLDB` to debug. Although I'm not an expert in `C++` and I can't say for sure why it operates this way, but I guess it might be of `C++`  "by design" features.

---

Meanwhile I published the [v1.0.0](https://github.com/winseros/Qt6RendererVsc/releases/tag/v1.0.0) version of the extension and thus I consider this issue closed.

**Comment by Merrit** [comment]
@winseros Agreed. Thanks so much for all your hard work! :bowing_woman: I appreciate you :blue_heart: :)
